spring:
  datasource:
    init: false #variavel criada para controle de iniciaização do DB dependendo do cenario (test, prod, dev...)
  jpa:
    hibernate:
      ddl-auto: create-drop

jwt:
  secret: 123456