# Para push direto na master (segurança 'rules' desabilitada)

name: 'Push Master: Build, Test'

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 19
          distribution: 'temurin'
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Gradle Clean
        run: ./gradlew clean

      - name: Gradle Build e Testes
        run: ./gradlew build
